name: provider_app
description: "A service provider app for Nsaano Business."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_screenutil: ^5.5.1
  font_awesome_flutter: ^10.2.0  # Add Font Awesome dependency here
  hugeicons: ^0.0.1
  http: ^1.3.0  # Add the http package for network requests
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2 # Use the latest version
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  provider: ^6.1.1  # Add provider package for state management
  permission_handler: ^11.4.0 # Add permission_handler for location permissions
  device_info_plus: ^11.3.3
  # Location package
  location: ^8.0.0
  location_platform_interface: ^6.0.0
  location_web: ^6.0.0
  permission_handler_android: ^12.1.0
  image_picker_for_web: ^3.0.6
  js: ^0.7.2
  mime: ^2.0.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  geolocator_android: ^5.0.1
  logger: ^2.5.0
  intl: ^0.20.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  # Ensure the following line includes the necessary material design
  uses-material-design: true

  # Assets setup
  assets:
    - assets/images/

# Flutter launcher icon configuration
  

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true
  image_path: "assets/images/nsaano_logo3.png"

dependency_overrides:
  geolocator_android: ^5.0.1
  async: ^2.13.0
  fake_async: ^1.3.3
  material_color_utilities: ^0.12.0
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0
